import type { Metadata } from "next";
import Navbar from "./components/Navbar";
import "./globals.css";
import Footer from "./Footer";
import {CartProvider} from "./data/CartContext";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className="antialiased bg-black min-h-screen flex flex-col w-full overflow-x-hidden"
      >
        <CartProvider>
          <Navbar/>
          <main className="flex-1 w-full">{children}</main>
          <Footer />
        </CartProvider>
        
      </body>
    </html>
  );
}
